### ISSUE TITLE
Customizing last paragraph is wrong / confusing

### ISSUE THREAD

**Issue by SimonLSchlee** [spdegabrielle/qi-quickscripts#4]
> Scripts can be selectively deactivated from the library (Scripts|Manage scripts|Library).
> 
> If you change the source code of a script installed from the quickscript-extra package (or from any package containing quickscripts), you will lose all your modifications when the package is updated. To avoid this, you can use Quickscript’s shadow scripts: The shadow script calls the original script without modifying it, and can be modified to your taste without being modified when the original script is updated.
> 
> In particular, if you want to change the default label, menu path or keybinding of a script installed from quickscript-extra, go to Scripts|Manage|Library…, select the qi-quickscripts directory, then the script you want, and click on Shadow. This opens a new (shadow) script that calls the original script where you can change what you want.

It first talks about quickscript-extra then about qi-quickscripts. (lowercase because I forgot to replace the one in the readme)
My suggestion:
1. replace both with `Qi-Quickscripts`, because it is less confusing when the documentation of a package doesn't talk about unrelated package names (I think, but could be wrong).
2. or have `quickscript-extra` everywhere.

This paragraph is both in the documentation and readme.
I can make this change let me know what you think. @spdegabrielle

**Comment by countvajhula** [comment]
@SimonLSchlee It looks like the first mention of `quickscript-extra` talks about the general feature of being able to "shadow" quickscripts, and then the second part about `Qi-Quickscripts` gives the specific instructions of how to shadow for this package.

<img width="798" alt="Screen Shot 2022-05-02 at 12 48 50 PM" src="https://user-images.githubusercontent.com/401668/166315415-df24ae7d-4752-4032-8881-7be12525b3d9.png">

But I can see how mentioning the two packages without explicitly pointing out this distinction could be confusing. Maybe something like

"In particular, if you want to change the default label, menu path or keybinding of a script installed from quickscript-extra, go to Scripts|Manage|Library…, select the directory corresponding to the package you are interested in customizing (e.g. in this case Qi-Quickscripts), ..."

could be more clear?

**Comment by SimonLSchlee** [comment]
My argument was that "quickscript-extra" followed by select "Qi-Quickscripts" makes it unnecessarily complicated, the reader shouldn't have to understand oh they were talking about editing the first in general terms, now they are talking about editing this package in specific terms. I thought it would be better if it was just with one package name.

I think that this would make it easier to read.

I like your description it also serves double purpose, so that we don't have to mention two different packages/directories
and it should still be clear that you can do this with others as well.

with one package:
"In particular, if you want to change the default label, menu path or keybinding of a script installed from Qi-Quickscript, go to Scripts|Manage|Library…, select the directory corresponding to the package you are interested in customizing (e.g. in this case Qi-Quickscripts), then the script you want, and click on Shadow. This opens a new (shadow) script that calls the original script where you can change what you want."

@countvajhula do you agree with this?

**Comment by countvajhula** [comment]
@SimonLSchlee Oh I see, I was actually confusing `quickscript-extra` with the Quickscript package itself! In that case, I like your original suggestion better -- i.e. let's just use `Qi-Quickscripts` everywhere instead of `quickscript-extra`. I suspect that is probably an accidental leftover from [the template](https://github.com/spdegabrielle/quickscript-extra) that @spdegabrielle used.

**Comment by SimonLSchlee** [comment]
@countvajhula I agree, I have merged the changes.

**Comment by countvajhula** [comment]
@SimonLSchlee Thank you for taking the lead on this!

**Comment by SimonLSchlee** [comment]
@countvajhula You are welcome! This made me laugh, because I had to think of the Quake III anouncer: https://www.youtube.com/watch?v=wc0EtpqwCjU
